#! /usr/bin/env sh

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

declare -i ERR_CODE=$STATE_OK

HOSTNAME="$1"
PORT="$2"
CONFIG="/etc/icinga/ssh_config"
SOCKET="/var/run/icinga/ssh@${HOSTNAME}:${PORT}.sock"
KEY="/etc/icinga/nagios_sshkey"

if [ $# -lt 2 ]; then
  echo "usage: $(basename "$0") <host> <port>"
  exit
fi

if [ -S "${SOCKET}" ]; then
  ERR_MSG="OK - Tunnel exists"
  ERR_CODE=$STATE_OK
elif [ ! -f "${KEY}" ]; then
  ERR_MSG="CRITICAL - keyfile missing: ${KEY}"
  ERR_CODE=$STATE_CRITICAL
elif [ ! -d "$(dirname "${SOCKET}")" ]; then
  ERR_MSG="CRITICAL - socket directory missing: $(dirname "${SOCKET}")"
  ERR_CODE=$STATE_CRITICAL
else
  # start ssh with all file descriptors closed/nulled so that the check doesn't hang
  /usr/bin/ssh -nNMf -p "${PORT}" -i "${KEY}" -F "${CONFIG}" "${HOSTNAME}" >/dev/null 2>&1 3>&- 4>&- 5>&- 6>&-
  if [ $? -ne 0 ] ; then
    ERR_MSG="CRITICAL - Tunnel creation failed"
    ERR_CODE=$STATE_CRITICAL
  else
    ERR_MSG="OK - Tunnel established"
    ERR_CODE=$STATE_OK
  fi
fi

echo "$ERR_MSG"
exit $ERR_CODE
