#! /usr/bin/env bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin

declare OUTPUT=""

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

declare -i NUM=0
declare -i NUM_OK=0
declare -i NUM_WARN=0
declare -i NUM_CRIT=0

declare -a IGNORE

for ARG in "$@"; do
  if [[ "$ARG" =~ ^--ignore= ]]; then
    IGNORE+=("${ARG#--ignore=}")
  fi
done

LIST="$(virsh list --all | sed -e '1,2d' -e '/^$/d'| awk '{ print $2":"$3 }')"

if [ -n "$LIST" ]; then
  for HOST_LINE in $LIST; do
    HOST_NAME="$(awk -F: '{ print $1 }' <<<${HOST_LINE})"
    STATE="$(awk -F: '{print $2}' <<<${HOST_LINE})"
    NUM=$(expr $NUM + 1)

    NOCHECK=false

    for IGNORED_HOST in "${IGNORE[@]}"; do
      if [ "$IGNORED_HOST" = "$HOST_NAME" ]; then
        NOCHECK=true
        break
      fi
    done

    if $NOCHECK; then
      NUM_OK=$(expr $NUM_OK + 1)
      continue
    fi

    case "$STATE" in
      running|blocked)
        NUM_OK=$(expr $NUM_OK + 1)
      ;;
      paused)
        NUM_WARN=$(expr $NUM_WARN + 1)
        OUTPUT="${OUTPUT}${HOST_NAME} "
      ;;
      shutdown|shut*|crashed|*)
        NUM_CRIT=$(expr $NUM_CRIT + 1)
        OUTPUT="${OUTPUT}${HOST_NAME} "
      ;;
    esac
  done
else
  echo "Unknown guests!"
  exit ${STATE_UNKNOWN}
fi

if [ $NUM -eq $NUM_OK ]; then
  echo "${NUM_OK}/${NUM} running"
  exit $STATE_OK
elif [ $NUM_CRIT -gt 0 ]; then
  echo "${NUM_OK}/${NUM} running, ${NUM_WARN}/${NUM} paused, ${NUM_CRIT}/${NUM} broken: $OUTPUT"
  exit $STATE_CRITICAL
elif [ $NUM_WARN -gt 0 ]; then
  echo "${NUM_OK}/${NUM} running, ${NUM_WARN}/${NUM} paused, ${NUM_CRIT}/${NUM} broken: $OUTPUT"
  exit $STATE_WARNING
fi
