#! /usr/bin/env bash

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

NODEJS_HOMEPAGE="http://nodejs.org/download/"
NODEJS_BIN="node"

[ -n "$1" ] && NODEJS_BIN="$1"

UPSTREAM_VER="$(wget -q -O - -- ${NODEJS_HOMEPAGE} | grep 'Current version:' | sed -e 's/<[a-zA-Z\/][^>]*>//g' | sed 's/^ *//g' | sed 's/ $//g' | awk '{ print $3 }')"
LOCAL_VER="$(${NODEJS_BIN} -v 2>/dev/null)"

if [ -z "$LOCAL_VER" ]; then
  ERR_MSG="Could not determine local node.js version!"
  ERR_CODE=$STATE_UNKNOWN
elif [ -z "$UPSTREAM_VER" ]; then
  ERR_MSG="Could not determine remote node.js version!"
  ERR_CODE=$STATE_UNKNOWN
else
  if [ "$LOCAL_VER" != "$UPSTREAM_VER" ]; then
    ERR_MSG="Local node.js is not up to date (${LOCAL_VER} vs. ${UPSTREAM_VER})"
    ERR_CODE=$STATE_CRITICAL
  fi
fi

if [ -n "$ERR_MSG" ]; then
  echo -e "ERROR: $ERR_MSG"
  exit $ERR_CODE
else
  echo "OK: Local node.js is up to date"
  exit $STATE_OK
fi
