#!/usr/bin/env bash

# Copyright (c) 2014 Jan-Philipp Litza <janphilipp@litza.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e
set -u

. /usr/lib/nagios/plugins/utils.sh

declare -i totalpeers=0
declare downpeers=""
declare pattern="${1:-*}"

while read name proto table state since info; do
    totalpeers=$(($totalpeers + 1))
    if [ "$state" != "up" ]; then
        downpeers="${downpeers}${name} "
    fi
done <<< "$(sudo birdc -r show protocols "\"$pattern\""|tail -n+4)"

if [ -z "$downpeers" ]; then
    echo "[OK] $totalpeers BGP peerings are up"
    exit $STATE_OK
else
    echo -e "[CRITICAL] $downpeers"
    exit $STATE_CRITICAL
fi
