#! /usr/bin/env bash

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

declare -i ERR_CODE=$STATE_OK

SEARCH_DIR="$1"

if [ -z "$SEARCH_DIR" ]; then
  ERR_MSG="No search directory given!"
  ERR_CODE=$STATE_UNKNOWN
else
  UPSTREAM_VER=$(curl -s http://api.wordpress.org/core/version-check/1.5/ | head -n 4 | tail -n 1)

  if [ -z "$UPSTREAM_VER" ]; then
    ERR_MSG="Could not get remote version!"
    ERR_CODE=$STATE_UNKNOWN
  else
    for file in $(find ${SEARCH_DIR} -type f -name wp-config.php); do
      LOCAL_DIR=$(dirname "$file")
      if grep -q '^\$wp_version' ${LOCAL_DIR}/wp-includes/version.php; then
        dirname "$file" | grep -q '\.bu' && continue
        LOCAL_VER=$(grep '^\$wp_version' ${LOCAL_DIR}/wp-includes/version.php | cut -d "'" -f 2)
        if [ "$LOCAL_VER" != "$UPSTREAM_VER" ]; then
          ERR_CODE=$STATE_CRITICAL
          ERR_MSG="${ERR_MSG}${LOCAL_DIR} is not up to date (${LOCAL_VER} vs. ${UPSTREAM_VER}), "
        fi
      fi
    done
  fi
fi

if [ -n "$ERR_MSG" ]; then
  echo "ERROR: $ERR_MSG" | sed 's/, $//g'
else
  echo "OK: all local WordPress are up to date"
fi

exit $ERR_CODE
