#! /usr/bin/env bash
# 2014, Moritz Kaspar Rudert (mortzu) <mr@planetcyborg.de>.
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this list of
#   conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this list
#   of conditions and the following disclaimer in the documentation and/or other materials
#   provided with the distribution.
#
# * The names of its contributors may not be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# * Feel free to send Club Mate to support the work.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
# AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -e

PATH=/sbin:/usr/sbin:/bin:/usr/bin

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3
declare -i STATE_DEPENDENT=4

declare -i ERR_CODE=${STATE_UNKNOWN}
declare ERR_MSG

declare -i PROBLEMS=0

declare -a WHITELIST_IPV4
declare -a WHITELIST_IPV6
declare -a WHITELIST_HTTP

declare CHECK_HTTP="/usr/lib/nagios/plugins/check_http"
declare CHECK_HTTP_OPTS=""

declare -i ret=0

declare WEBSERVER="apache"

for ARG in "$@"; do
  if [[ "$ARG" =~ ^--no-ipv4= ]]; then
    WHITELIST_IPV4+=("${ARG#--no-ipv4=}")
  elif [[ "$ARG" =~ ^--no-ipv6= ]]; then
    WHITELIST_IPV6+=("${ARG#--no-ipv6=}")
  elif [[ "$ARG" =~ ^--allow-all= ]]; then
    WHITELIST_HTTP+=("${ARG#--allow-all=}")
  elif [[ "$ARG" =~ ^--webserver= ]]; then
    WEBSERVER="${ARG#--webserver=}"
  fi
done

if [ "$WEBSERVER" = "lighttpd" ]; then
  DOMAINS="$(lighttpd -p -f /etc/lighttpd/lighttpd.conf | grep '$HTTP\["host"\] == ' | cut -d'"' -f4 | sort -u)"
else
  DOMAINS="$(apache2ctl -S 2>/dev/null | awk '/ namevhost / { print $4 }')"
fi

for DOMAIN in $DOMAINS; do
  for IP_VERSION in 4 6; do
    VERIFY=true
    HTTP_VERIFY=true

    if [ $IP_VERSION -eq 4 ]; then
      for WHITELISTED in "${WHITELIST_IPV4[@]}"; do
        if [ "$WHITELISTED" = "$DOMAIN" ]; then
          VERIFY=false
          break
        fi
      done
    else
      for WHITELISTED in "${WHITELIST_IPV6[@]}"; do
        if [ "$WHITELISTED" = "$DOMAIN" ]; then
          VERIFY=false
          break
        fi
      done
    fi

    if $VERIFY; then
      for WHITELISTED in "${WHITELIST_HTTP[@]}"; do
        if [ "$WHITELISTED" = "$DOMAIN" ]; then
          HTTP_VERIFY=false
          break
        fi
      done

      if [ "${IP_VERSION}" = "4" ]; then
        IP_ADDRESS="127.0.0.1"
      else
        IP_ADDRESS="::1"
      fi

      if $HTTP_VERIFY; then
        set +e
        DOM_MSG="$(${CHECK_HTTP} -${IP_VERSION} -I ${IP_ADDRESS} ${CHECK_HTTP_OPTS} -H ${DOMAIN})"
        ret=$?
        set -e
      else
        set +e
        DOM_MSG="$(${CHECK_HTTP} -${IP_VERSION} -I ${IP_ADDRESS} ${CHECK_HTTP_OPTS} -H ${DOMAIN} -e 'HTTP/1.')"
        ret=$?
        set -e
      fi

      if [ ${ret} -eq 0 ]; then
        # no problem
        true
      elif [ ${ret} -eq 1 ]; then
        PROBLEMS=$((${PROBLEMS}+1))
        [ -n "${DOM_MSG}" ] && ERR_MSG="${ERR_MSG}\n${DOMAIN} (IPv${IP_VERSION}): ${DOM_MSG}"
        if [ ${ERR_CODE} -eq 0 ]; then
          ERR_CODE=${ret}
        elif [ ${ERR_CODE} -gt 2 ]; then
          ERR_CODE=${ret}
        fi
      elif [ ${ret} -eq 2 ]; then
        PROBLEMS=$((${PROBLEMS}+1))
        [ -n "${DOM_MSG}" ] && ERR_MSG="${ERR_MSG}\n${DOMAIN} (IPv${IP_VERSION}): ${DOM_MSG}"
        ERR_CODE=${ret}
      elif [ ${ret} -eq 3 ]; then
        PROBLEMS=$((${PROBLEMS}+1))
        [ -n "${DOM_MSG}" ] && ERR_MSG="${ERR_MSG}\n${DOMAIN} (IPv${IP_VERSION}): ${DOM_MSG}"
        if [ ${ERR_CODE} -eq 0 ]; then
          ERR_CODE=${ret}
        fi
      elif [ ${ret} -eq 4 ]; then
        PROBLEMS=$((${PROBLEMS}+1))
        [ -n "${DOM_MSG}" ] && ERR_MSG="${ERR_MSG}\n${DOMAIN} (IPv${IP_VERSION}): ${DOM_MSG}"
        if [ ${ERR_CODE} -eq 0 ]; then
          ERR_CODE=${ret}
        fi
      else
        PROBLEMS=$((${PROBLEMS}+1))
        ERR_MSG="${ERR_MSG}\nGot unknown return value ${ret} for domain ${DOMAIN}"
        [ -n "${DOM_MSG}" ] && ERR_MSG="${ERR_MSG}\n${DOMAIN} (IPv${IP_VERSION}): ${DOM_MSG}"
      fi
    fi
  done
done

if [ ${PROBLEMS} -eq 0 ]; then
  ERR_CODE=${STATE_OK}
fi

ERR_MSG="Found ${PROBLEMS} problems${ERR_MSG}"
echo -e ${ERR_MSG}
exit ${ERR_CODE}
