#! /usr/bin/env bash

if [ ! -f /etc/rkhunter.conf ]; then
  ERR_MSG="rkhunter.conf not found. So probably rkhunter is not installed!"
  ERR_CODE=1
else
  ERR_MSG="rkhunter.conf found. So rkhunter is installed."
  ERR_CODE=0
fi

if [ $ERR_CODE -eq 0 ]; then
  echo "OK: $ERR_MSG"
else
  echo "ERROR: $ERR_MSG"
fi

exit $ERR_CODE
