#! /usr/bin/env bash

SEARCH_DIR="$1"

if [ -z "$SEARCH_DIR" ]; then
  ERR_MSG="No search directory given!"
  ERR_CODE=1
else
  UPSTREAM_VER=$(curl -s http://www.cmsmadesimple.org | grep 'Download ' | grep -o '<a .*href=.*downloads.*>' | sed -r 's#^.*<a href="([^"]+)">([^<]+)</a>.*$#\2#' | awk '{ print $2 }')

  if [ -z "$UPSTREAM_VER" ]; then
    ERR_MSG="Could not get remote CMS Made Simple version!"
    ERR_CODE=1
  else
    for cms in $(find ${SEARCH_DIR} -type f -name version.php); do
      if grep -q 'CMS_VERSION' "$cms"; then
        dirname "$cms" | grep -q '\.bu' && continue
        LOCAL_DIR=$(dirname "$cms")
        LOCAL_VER=$(cat "$cms" | grep 'CMS_VERSION = ' | awk '{ print $3 }' | sed -e 's/"//g' -e 's/;//g')
        if [ "$LOCAL_VER" != "$UPSTREAM_VER" ]; then
          ERR_CODE=2
          ERR_MSG="${ERR_MSG}${LOCAL_DIR} is not up to date (${LOCAL_VER} vs. ${UPSTREAM_VER}), "
        fi
      fi
    done
  fi
fi

if [ -n "$ERR_MSG" ]; then
  echo -e "ERROR: $ERR_MSG" | sed 's/, $//g'
  exit $ERR_CODE
else
  echo "OK: all local CMS Made Simple are up to date"
  exit 0
fi
