#! /usr/bin/env bash

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

declare -i ERR_CODE=$STATE_OK

SOFTWARE_NAME="Tiny Tiny RSS"
SEARCH_DIR="$1"

OLD_IFS="${IFS}"
IFS="
"

if [ -z "$SEARCH_DIR" ]; then
  ERR_MSG="No search directory given!"
  ERR_CODE=$STATE_UNKNOWN
else
  UPSTREAM_VER=$(curl -s http://tt-rss.org/version.php | python -c "import json; import sys; data=json.load(sys.stdin); print data['version']")

  if [ -z "$UPSTREAM_VER" ]; then
    ERR_MSG="Could not get remote version!"
    ERR_CODE=$STATE_UNKNOWN
  else
    for file in $(find ${SEARCH_DIR} \( -type d -name '*.bu' -prune \) -o \( -type f -name functions.php -print \)); do
      LOCAL_DIR=$(dirname "$file" | sed 's#/include##g')
      if grep -q 'http://tt-rss.org/version.php' "$file"; then
        dirname "$file" | grep -q '\.bu' && continue
        LOCAL_VER=$(grep "define('VERSION" "${LOCAL_DIR}/include/version.php" 2>/dev/null | head -n1 | cut -d "'" -f 4)
        LOCAL_VER2=$(grep "define('VERSION" "${LOCAL_DIR}/version.php" 2>/dev/null | head -n1 | cut -d '"' -f 2)
        [ -z "$LOCAL_VER" ] && [ -z "$LOCAL_VER2" ] && continue || LOCAL_VER=$LOCAL_VER2
        if [ "$LOCAL_VER" != "$UPSTREAM_VER" ]; then
          ERR_CODE=$STATE_CRITICAL
          ERR_MSG="${ERR_MSG}${LOCAL_DIR} is not up to date (${LOCAL_VER} vs. ${UPSTREAM_VER}), "
        fi
      fi
    done
  fi
fi

IFS="${OLD_IFS}"

case $ERR_CODE in
  $STATE_OK)
    echo "OK: all local ${SOFTWARE_NAME} are up to date (${UPSTREAM_VER})"
    ;;
  $STATE_UNKNOWN)
    echo "UNKNOWN: $ERR_MSG"
    ;;
  $STATE_CRITICAL)
    echo "ERROR: Not up to date (${UPSTREAM_VER}): ${ERR_MSG}" | sed 's/, $//'
    ;;
esac

exit $ERR_CODE
