#! /usr/bin/env bash
# 2014, Moritz Kaspar Rudert (mortzu) <mr@planetcyborg.de>.
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this list of
#   conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this list
#   of conditions and the following disclaimer in the documentation and/or other materials
#   provided with the distribution.
#
# * The names of its contributors may not be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# * Feel free to send Club Mate to support the work.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
# AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

declare -i ERR_CODE=$STATE_OK
declare -i HOSTS=0
declare -i HOSTS_UP=0

declare -a INTERFACE_WHITELIST

IP_BIN="$(which ip)"

for ARG in "$@"; do
  if [[ "$ARG" =~ ^--no-check= ]]; then
    INTERFACE_WHITELIST+=("${ARG#--no-check=}")
  fi
done

for INTERFACE in $($IP_BIN -o addr show | grep 'inet ' | grep ' peer ' | awk '{ print $2 }'); do
  VERIFY=true
  for WHITELISTED in "${INTERFACE_WHITELIST[@]}"; do
    if [ "$WHITELISTED" = "$INTERFACE" ]; then
      VERIFY=false
      break
    fi
  done

  if $VERIFY; then
    HOSTS=$(($HOSTS+1))
    IP_ADDRESS="$($IP_BIN -o addr show dev $INTERFACE | grep 'inet ' | awk '{ print $6 }' | awk -F'/' '{ print $1 }')"

    if ! ping -W4 -c2 "$IP_ADDRESS" >/dev/null 2>&1; then
      ERR_CODE=$STATE_CRITICAL
      ERR_MSG="${ERR_MSG}${INTERFACE}, "
    else
      HOSTS_UP=$(($HOSTS_UP+1))
    fi
  fi
done

if [ $ERR_CODE -eq $STATE_OK ]; then
  echo "OK: $HOSTS_UP of $HOSTS peerings are up"
else
  echo "ERROR: $ERR_MSG" | sed 's/, $//'
fi

exit $ERR_CODE
