#! /usr/bin/env sh
# 2014, Moritz Kaspar Rudert (mortzu) <mr@planetcyborg.de>.
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this list of
#   conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this list
#   of conditions and the following disclaimer in the documentation and/or other materials
#   provided with the distribution.
#
# * The names of its contributors may not be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# * Feel free to send Club Mate to support the work.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
# AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

BACKUP_DIR="$1"
WARN_AGE="$2"
CRIT_AGE="$3"
MAXDEPTH="$4"

usage() {
  cat <<EOF
Usage: $(basename $0) <dir> <warn> <crit> [<maxdepth>]

<dir> is the directory to look in for backups
<warn> is the maximum age of the newest backup before the state is warning
<crit> is the maximum age of the newest backup before the state is critical
<maxdepth> is the maximum search depth and optional (but very recommended for
           file backups)
EOF
}

if [ "$#" -lt 3 ]; then
  usage
  exit $STATE_UNKNOWN
elif ! [ -e "$BACKUP_DIR" ]; then
  echo "${BACKUP_DIR} does not exist!"
  usage
  exit $STATE_UNKNOWN
elif [ "$WARN_AGE" -gt "$CRIT_AGE" ]; then
  echo "Warning age ${WARN_AGE} is greater than critical age ${CRIT_AGE}!"
  usage
  exit $STATE_UNKNOWN
elif [ "$WARN_AGE" -eq 0 ]; then
  echo "Warning age is 0! That doesn't make sense, you know..."
  usage
  exit $STATE_UNKNOWN
elif [ "$CRIT_AGE" -eq 0 ]; then
  echo "Critical age is 0! That doesn't make sense, you know..."
  usage
  exit $STATE_UNKNOWN
fi

has_files() {
  find "$BACKUP_DIR" ${MAXDEPTH:+-maxdepth $MAXDEPTH} -mtime "-$1" -printf '#'|grep '#' > /dev/null
}

if ! has_files "$CRIT_AGE"; then
  echo "CRITICAL: Newest backup older than ${CRIT_AGE} days"
  exit $STATE_CRITICAL
elif ! has_files "$WARN_AGE"; then
  echo "WARNING: Newest backup older than ${WARN_AGE} days"
  exit $STATE_WARNING
else
  echo "OK: Newest backup not older than ${WARN_AGE} days"
  exit $STATE_OK
fi
