#!/usr/bin/env bash

# Copyright (c) 2014 Jan-Philipp Litza <janphilipp@litza.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e
set -u

. /usr/lib/nagios/plugins/utils.sh

declare -i PEERS_TOTAL=0
declare PEERS_DOWN=''
declare PATTERN="${1:-*}"

while read NAME PROTO TABLE STATE SINCE INFO; do
  if [ "$PROTO" != 'BGP' ]; then
    continue
  fi

  PEERS_TOTAL=$((${PEERS_TOTAL} + 1))
  if [ "$STATE" != 'up' ]; then
    PEERS_DOWN="${PEERS_DOWN}${NAME} "
  fi
done <<< "$(birdc -r show protocols "\"$PATTERN\"" | tail -n+4)"

if [ -z "$PEERS_DOWN" ]; then
  echo "[OK] ${PEERS_TOTAL} BGP peerings are up"
  exit $STATE_OK
else
  echo -e "[CRITICAL] ${PEERS_DOWN}"
  exit $STATE_CRITICAL
fi
