#! /usr/bin/env bash
# 2014, Moritz Kaspar Rudert (mortzu) <mr@planetcyborg.de>.
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this list of
#   conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this list
#   of conditions and the following disclaimer in the documentation and/or other materials
#   provided with the distribution.
#
# * The names of its contributors may not be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# * Feel free to send Club Mate to support the work.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
# AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# nagios exit codes
declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

# initial curl parameters
CURL_PARAM=""

# http code expected for return code 0
CURL_EXPECTED="200"

# little help function
show_help() {
  cat >&2 << EOF
check_http_curl v0.0.1
Copyright (c) 2013 Moritz Rudert <helios@planetcyborg.de>

Usage:
$0 -u <uri> [-a auth] [-t <timeout>] [-e <expect>] [-4|-6]

Options:
 -h
  Print detailed help screen
 -4
  Use IPv4 connection
 -6
  Use IPv6 connection
 -e STRING
  expected statuscode for exit 0
 -u <uri>
  URL to GET
 -a AUTH_PAIR
  Username:password on sites with authentication
 -A STRING
  String to be sent in http header as "User Agent"
EOF

  [ -n "$1" ] && { echo >&2; echo "$1" >&2; }

  exit 1
}

# parsing commandline parameters
while getopts ":a:u:e:h46A:" opt; do
  case $opt in
    a)
      CURL_PARAM="$CURL_PARAM --anyauth -u $OPTARG"
    ;;
    u)
      CURL_URL="$OPTARG"
    ;;
    e)
      CURL_EXPECTED="$OPTARG"
    ;;
    h)
      show_help
    ;;
    4)
      CURL_PARAM="$CURL_PARAM -4"
    ;;
    6)
      CURL_PARAM="$CURL_PARAM -6"
    ;;
    A)
      CURL_PARAM="$CURL_PARAM -A $OPTARG"
    ;;
    \?)
      show_help "Invalid option: -$OPTARG"
    ;;
    :)
      show_help "Option -$OPTARG requires an argument."
    ;;
  esac
done

# if no URL to test specified, show help and exit
[ -z "$CURL_URL" ] && show_help "No URL defined!"
[ -x "$(which curl)" ] || show_help "curl not found!"

# curl magic
CURL_OUTPUT=($(curl -sSqm 10 -w "%{http_code}\\n%{size_download}\\n%{time_total}\\n" $CURL_PARAM "$CURL_URL" -o /dev/null --stderr -))

# if curl exited unexpected
if [ $? -ne 0 ]; then
  # unset unneeded elements of array
  for i in $(seq 0 3); do
    unset -v CURL_OUTPUT[$i]
  done

  echo "${CURL_OUTPUT[@]}"
  exit $STATE_CRITICAL
fi

# output
echo "${CURL_OUTPUT[0]} - ${CURL_OUTPUT[1]} bytes in ${CURL_OUTPUT[2]} seconds response time"
# HTTP WARNING: HTTP/1.1 401 Authorization Required - 734 bytes in 0.034 second response time |time=0.034063s;;;0.000000 size=734B;;;0

# ...and exit code
if [ "${CURL_OUTPUT[0]}" = "$CURL_EXPECTED" ]; then
  exit $STATE_OK
else
  exit $STATE_WARNING
fi
