#! /usr/bin/env bash
# 2014, Moritz Kaspar Rudert (mortzu) <mr@planetcyborg.de>.
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this list of
#   conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice, this list
#   of conditions and the following disclaimer in the documentation and/or other materials
#   provided with the distribution.
#
# * The names of its contributors may not be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# * Feel free to send Club Mate to support the work.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
# AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

PATH=/sbin:/usr/sbin:/bin:/usr/bin

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

declare -i ERR_CODE=$STATE_OK

SOFTWARE_NAME="node.js"
if [ -n "$1" ]; then
  NODEJS_BIN="$1"
else
  NODEJS_BIN="$(which node)"
fi

if [ -z "$NODEJS_BIN" ]; then
  ERR_MSG="Could not find local ${SOFTWARE_NAME}!"
  ERR_CODE=$STATE_UNKNOWN
else
  UPSTREAM_VER=$(curl -f http://nodejs.org/download/ 2>/dev/null | grep 'Current version:' | sed -e 's/<[a-zA-Z\/][^>]*>//g' -e 's/^ *//g' -e 's/ $//g' | cut -d ' ' -f 3 | sed -e 's/^v//')
  LOCAL_VER="$(${NODEJS_BIN} -v 2>/dev/null | sed -e 's/^v//')"

  if [ -z "$LOCAL_VER" ]; then
    ERR_MSG="Could not get local version!"
    ERR_CODE=$STATE_UNKNOWN
  elif [ -z "$UPSTREAM_VER" ]; then
    ERR_MSG="Could not get remote version!"
    ERR_CODE=$STATE_UNKNOWN
  else
    if [ "$LOCAL_VER" != "$UPSTREAM_VER" ]; then
      LOCAL_DIR="$(dirname ${NODEJS_BIN})"
      ERR_MSG="${NODEJS_BIN##$LOCAL_DIR} (${LOCAL_VER})"
      ERR_CODE=$STATE_CRITICAL
    fi
  fi
fi

case $ERR_CODE in
  $STATE_OK)
    echo "OK: all local ${SOFTWARE_NAME} are up to date (${UPSTREAM_VER})"
  ;;
  $STATE_UNKNOWN)
    echo "UNKNOWN: $ERR_MSG"
  ;;
  $STATE_CRITICAL)
    echo "ERROR: Not up to date (${UPSTREAM_VER}): ${ERR_MSG}" | sed 's/, $//'
  ;;
esac

exit $ERR_CODE
