#! /usr/bin/env bash

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

declare -i ERR_CODE=$STATE_OK

SOFTWARE_NAME="Roundcube webmailer"
SEARCH_DIR="$1"

OLD_IFS="${IFS}"
IFS="
"

if [ -z "$SEARCH_DIR" ]; then
  ERR_MSG="No search directory given!"
  ERR_CODE=$STATE_UNKNOWN
else
  UPSTREAM_VER=$(curl -s http://www.roundcube.net | grep 'Download now' | grep -o '<a .*href=.*download.*>' | sed -r 's#^.*<a (.*)>([^<]+)</a>.*$#\2#' | awk '{ print $2 }')

  if [ -z "$UPSTREAM_VER" ]; then
    ERR_MSG="Could not get remote version!"
    ERR_CODE=$STATE_UNKNOWN
  else
    for file in $(find ${SEARCH_DIR} \( -type d -name '*.bu' -prune \) -o \( -type f -name iniset.php -print \)); do
      LOCAL_DIR=$(dirname "$file" | sed 's#/program/include##g')
      if grep -q 'RCMAIL_VERSION' "$file"; then
        LOCAL_VER=$(grep "define('RCMAIL_VERSION'" "$file" | cut -d "'" -f 4)
        if [ "$LOCAL_VER" != "$UPSTREAM_VER" ]; then
          ERR_CODE=$STATE_CRITICAL
          ERR_MSG="${ERR_MSG}${LOCAL_DIR##$SEARCH_DIR} (${LOCAL_VER}), "
        fi
      fi
    done
  fi
fi

IFS="${OLD_IFS}"

case $ERR_CODE in
  $STATE_OK)
    echo "OK: all local ${SOFTWARE_NAME} are up to date (${UPSTREAM_VER})"
    ;;
  $STATE_UNKNOWN)
    echo "UNKNOWN: $ERR_MSG"
    ;;
  $STATE_CRITICAL)
    echo "ERROR: Not up to date (${UPSTREAM_VER}): ${ERR_MSG}" | sed 's/, $//'
    ;;
esac

exit $ERR_CODE
