#! /usr/bin/env bash

# Copyright (c) 2015 Ingo Sieverdingbeck <ingo@sieverdingbeck.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

export TERM=linux

set -eu

declare -i STATE_OK=0
declare -i STATE_WARNING=1
declare -i STATE_CRITICAL=2
declare -i STATE_UNKNOWN=3

declare -i WARN_LEVEL=1
declare -i CRIT_LEVEL=3

PACMAN_NAME="yaourt"

PACMAN="$(which "${PACMAN_NAME}")"
PACMAN_OPTS="-Sud --print"

if [ ! -x "${PACMAN}" ]; then
  echo "[UNKNOWN] Found no executable pacman"
  exit ${STATE_UNKNOWN}
fi

result="$("${PACMAN}" ${PACMAN_OPTS})"

declare -i lines=$(echo "${result}" | wc -l)
lines=$((${lines} - 1))

if echo "${result}" | grep "there is nothing to do" &> /dev/null; then
  lines=0
fi

if [ ${lines} -lt 0 ]; then
  echo "[UNKNOWN] Got unexpected zero line result"
  exit ${STATE_UNKNOWN}
elif [ ${lines} -eq 0 ]; then
  echo "[OK] No updates available"
  exit ${STATE_OK}
elif [ ${lines} -ge ${CRIT_LEVEL} ]; then
  echo "[CRITICAL] ${lines} updates available"
  exit ${STATE_CRITICAL}
elif [ ${lines} -ge ${WARN_LEVEL} ]; then
  echo "[WARNING] ${lines} updates available"
  exit ${STATE_WARNING}
else
  echo "[UNKNOWN] Something gone wrong"
  exit ${STATE_UNKNOWN}
fi
